"""Runtime state machine and adapter contracts."""

from agenty.runtime.availability import (
    AvailabilityMachine,
    AvailabilityStateData,
    InvalidAvailabilityTransition,
)
from agenty.runtime.machine import RuntimeProbeMachine
from agenty.runtime.events import (
    InvalidRuntimeEventStream,
    RuntimeEventStreamMachine,
    RuntimeEventStreamState,
    RuntimeEventStreamStateData,
    RuntimeRawEventRecord,
)
from agenty.runtime.protocol import (
    AvailabilityEvent,
    AvailabilityState,
    CapabilityRecord,
    CapabilitySupport,
    ChannelEvent,
    ChannelMode,
    ChannelState,
    EvidenceLevel,
    OutputEvent,
    RuntimeEvent,
    RuntimeFailure,
    RuntimeFailureCode,
    RuntimeIdentity,
    RuntimeSnapshot,
    RuntimeTarget,
    RuntimeTurnRequest,
    SessionEvent,
    SessionState,
    TurnEvent,
    TurnState,
)
from agenty.runtime.turn import InvalidTurnTransition, TurnMachine, TurnStateData
from agenty.runtime.runner import RuntimeTurnRunner
from agenty.runtime.selection import (
    InvalidRuntimeSelection,
    RuntimeAdapterRegistry,
    RuntimeSelectionEvent,
    RuntimeSelectionEventName,
    RuntimeSelectionMachine,
    RuntimeSelectionState,
    RuntimeSelectionStateData,
)

__all__ = [
    "AvailabilityEvent",
    "AvailabilityMachine",
    "AvailabilityState",
    "AvailabilityStateData",
    "CapabilityRecord",
    "CapabilitySupport",
    "ChannelEvent",
    "ChannelMode",
    "ChannelState",
    "EvidenceLevel",
    "InvalidAvailabilityTransition",
    "InvalidTurnTransition",
    "InvalidRuntimeSelection",
    "InvalidRuntimeEventStream",
    "OutputEvent",
    "RuntimeEvent",
    "RuntimeEventStreamMachine",
    "RuntimeEventStreamState",
    "RuntimeEventStreamStateData",
    "RuntimeFailure",
    "RuntimeFailureCode",
    "RuntimeIdentity",
    "RuntimeProbeMachine",
    "RuntimeSnapshot",
    "RuntimeTarget",
    "RuntimeRawEventRecord",
    "RuntimeTurnRequest",
    "RuntimeTurnRunner",
    "RuntimeAdapterRegistry",
    "RuntimeSelectionEvent",
    "RuntimeSelectionEventName",
    "RuntimeSelectionMachine",
    "RuntimeSelectionState",
    "RuntimeSelectionStateData",
    "SessionEvent",
    "SessionState",
    "TurnEvent",
    "TurnMachine",
    "TurnState",
    "TurnStateData",
]
